version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    container_name: adotar_db
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: "${DB_DEV_USER}"
      POSTGRES_PASSWORD: "${DB_DEV_PASSWORD}"
      POSTGRES_DB: "${DB_DEV_NAME}"
    ports:
      - "5436:5432"
    env_file:
      - .env
    networks:
      - adotar-network
  adotar:
    image: adotar
    restart: always
    container_name: adotar
    build:
      context: .
      dockerfile: ./infrastructure/Dockerfile
    env_file:
      - .env
    environment:
      TZ: America/Sao_Paulo
      DB_DEV_URL: "${DB_DEV_URL}"
      DB_DEV_USER: "${DB_DEV_USER}"
      DB_DEV_PASSWORD: "${DB_DEV_PASSWORD}"
      JWT_DEV_SECRET: "${JWT_DEV_SECRET}"
      JWT_DEV_EXPIRATION: "${JWT_DEV_EXPIRATION}"
      MAIL_DEV_HOST: "${MAIL_DEV_HOST}"
      MAIL_DEV_PORT: "${MAIL_DEV_PORT}"
      MAIL_DEV_USERNAME: "${MAIL_DEV_USERNAME}"
      MAIL_DEV_PASSWORD: "${MAIL_DEV_PASSWORD}"
    ports:
      - "8086:8080"
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - adotar-network
networks:
  adotar-network:
    driver: bridge