server:
  port: 8888
spring:
  datasource:
    url: ${DB_DEV_URL}
    driver-class-name: org.postgresql.Driver
    username: ${DB_DEV_USER}
    password: ${DB_DEV_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      connection-timeout: 20000
      minimum-idle: 10
      maximum-pool-size: 50
      idle-timeout: 10000
      pool-name: PoolHikari
      auto-commit: false
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 100
  transaction:
    rollback-on-commit-failure: true
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        '[show_sql]': true
        '[format_sql]': true
        jdbc:
          batch_size: 4
        order_updates: true
        order_inserts: true
  session:
    jdbc:
      cleanup-cron: 0 0 4 * * *
  flyway:
    baseline-on-migrate: true
    locations:
      - classpath:db/migration
    fail-on-missing-locations: true
    baseline-version: 1

  #  mail:
  #    host: ${MAIL_DEV_HOST}
  #    port: ${MAIL_DEV_PORT}
  #    username: ${MAIL_DEV_USERNAME}
  #    password: ${MAIL_DEV_PASSWORD}
  #    properties:
  #      mail:
  #        smtp:
  #          auth: true
  #          socketFactory:
  #            port: 465
  #            class: javax.net.ssl.SSLSocketFactory
  #        starttls:
  #          enable: true
  web:
    locale-resolver: fixed
    locale: pt_BR
app:
  jwt-secret: ${JWT_DEV_SECRET}
  jwt-expiration-milliseconds: ${JWT_DEV_EXPIRATION}
#mail:
#  host: ${MAIL_DEV_HOST}
#  port: ${MAIL_DEV_PORT}
#  username: ${MAIL_DEV_USERNAME}
#  password: ${MAIL_DEV_PASSWORD}
