FROM openjdk:17-oracle
VOLUME /tmp
ADD /infrastructure/build/target/app.jar app.jar
EXPOSE 8080
RUN bash -c 'touch /app.jar'
ENTRYPOINT ["java", "-Djava.security.egd=file:/dev/./urandom", "-jar", "/app.jar"]