CREATE TABLE public.pets (
                             id bigserial NOT NULL,
                             active bool NOT NULL,
                             adoption_date timestamp(6) NULL,
                             color varchar(30) NULL,
                             created_at timestamp(6) NULL,
                             deleted_at timestamp(6) NULL,
                             description varchar(100) NULL,
                             gender varchar(6) NULL,
                             health_condition varchar(15) NULL,
                             is_available bool NOT NULL,
                             months_age int4 NULL,
                             name varchar(50) NULL,
                             serial_number varchar(25) NOT NULL,
                             "size" varchar(6) NULL,
                             updated_at timestamp(6) NULL,
                             visualizations int4 NULL,
                             years_age int4 NULL,
                             address_id int8 NULL,
                             breed_id int8 NULL,
                             type_id int8 NULL,
                             user_id int8 NULL,
                             CONSTRAINT pets_gender_check CHECK (((gender)::text = ANY ((ARRAY['FEMALE'::character varying, 'MALE'::character varying])::text[]))),
	CONSTRAINT pets_health_condition_check CHECK (((health_condition)::text = ANY ((ARRAY['CHRONIC_DISEASE'::character varying, 'INJURED'::character varying, 'SICK'::character varying, 'PREGNANT'::character varying, 'HEALTHY'::character varying])::text[]))),
	CONSTRAINT pets_pkey PRIMARY KEY (id),
	CONSTRAINT pets_size_check CHECK (((size)::text = ANY ((ARRAY['TINY'::character varying, 'SMALL'::character varying, 'MEDIUM'::character varying, 'LARGE'::character varying])::text[]))),
	CONSTRAINT uk_akqccfj8r7r61lqw7u0vc4arj UNIQUE (address_id),
	CONSTRAINT uk_trigk58g74vcbnbu005ysg00n UNIQUE (serial_number),
	CONSTRAINT fkc47kjb41qf50bwgddm024m5xn FOREIGN KEY (user_id) REFERENCES public.users(id),
	CONSTRAINT fkkysqluwbhpyx6dhgseh3kb0mt FOREIGN KEY (type_id) REFERENCES public.animal_types(id),
	CONSTRAINT fkr2wnqcmtrr16oaipocajcdn7w FOREIGN KEY (breed_id) REFERENCES public.breeds(id),
	CONSTRAINT fksm0k617sxctgmc1hp65vcih21 FOREIGN KEY (address_id) REFERENCES public.addresses(id)
);