CREATE TABLE
    public.breeds
(
    id             bigserial              NOT NULL,
    name           character varying(100) NOT NULL,
    animal_type_id bigint                 NULL
);

ALTER TABLE
    public.breeds
    ADD
        CONSTRAINT breeds_pkey PRIMARY KEY (id);

INSERT INTO public.breeds ("name", "animal_type_id")
VALUES ('S.R.D. (Sem Raça Definida)', '1'),
       ('Outro', '1'),
       ('Labrador Retriever', '1'),
       ('Bulldog Francês', '1'),
       ('Golden Retriever', '1'),
       ('Pastor Alemão', '1'),
       ('Poodle', '1'),
       ('Beagle', '1'),
       ('Boxer', '1'),
       ('Yorkshire Terrier', '1'),
       ('Dachshund (Cofap, Teckel ou Salsicha)', '1'),
       ('Rottweiler', '1'),
       ('Bulldog Inglês', '1'),
       ('Chihuahua', '1'),
       ('Bichon Frisé', '1'),
       ('Shih Tzu', '1'),
       ('Pug', '1'),
       ('Doberman', '1'),
       ('Border Collie', '1'),
       ('Bernese Mountain Dog (Cão de Montanha dos Pirineus)', '1'),
       ('Husky Siberiano', '1'),
       ('Maltese', '1'),
       ('Cocker Spaniel', '1'),
       ('Boston Terrier', '1'),
       ('Dalmatian (Dálmata)', '1'),
       ('Scottish Terrier', '1'),
       ('Shiba Inu', '1'),
       ('Weimaraner', '1'),
       ('Staffordshire Bull Terrier', '1'),
       ('Great Dane (Dogue Alemão)', '1'),
       ('Mastiff', '1'),
       ('Basset Hound', '1'),
       ('Australian Shepherd', '1'),
       ('Akita Inu', '1'),
       ('Rhodesian Ridgeback', '1'),
       ('Papillon', '1'),
       ('Cavalier King Charles Spaniel', '1'),
       ('Lhasa Apso', '1'),
       ('Greyhound', '1'),
       ('Shar-Pei', '1'),
       ('Irish Setter', '1'),
       ('Bichon Maltês', '1'),
       ('Staffordshire Bull Terrier Americano', '1'),
       ('Pastor Belga Malinois', '1'),
       ('Pomerânia', '1'),
       ('Setter Irlandês', '1'),
       ('Welsh Corgi Pembroke', '1'),
       ('Bloodhound', '1'),
       ('Dogue de Bordeaux', '1'),
       ('Basenji', '1'),
       ('Bull Terrier', '1'),
       ('Shetland Sheepdog', '1'),
       ('Puli', '1'),
       ('Lulu da Pomerânia (Spitz Alemão Anão)', '1'),
       ('West Highland White Terrier', '1'),
       ('Schnauzer Miniatura', '1'),
       ('Collie de Pelo Curto', '1'),
       ('Pastor de Shetland', '1'),
       ('Bichon Bolonhês', '1'),
       ('Mastim Napolitano', '1'),
       ('Whippet', '1'),
       ('Fox Terrier de Pelo Duro', '1'),
       ('Pastor de Beauce', '1'),
       ('Terrier Tibetano', '1'),
       ('Setter Gordon', '1'),
       ('Chow Chow', '1'),
       ('Galgo Afegão', '1'),
       ('Border Terrier', '1'),
       ('Pastor Maremano Abruzês', '1'),
       ('Havanese', '1'),
       ('Scottish Deerhound', '1'),
       ('Pequinês', '1'),
       ('Chesapeake Bay Retriever', '1'),
       ('Leonberger', '1'),
       ('Terrier Japonês', '1'),
       ('Buldogue Americano', '1'),
       ('Terrier Preto da Rússia', '1'),
       ('Braco Alemão', '1'),
       ('Lébrel Irlandês', '1'),
       ('S.R.D. (Sem Raça Definida)', '2'),
       ('Outro', '2'),
       ('Siamês', '2'),
       ('Persa', '2'),
       ('Maine Coon', '2'),
       ('Bengal', '2'),
       ('Ragdoll', '2'),
       ('Abissínio', '2'),
       ('Britânico de Pelo Curto', '2'),
       ('Exótico de Pelo Curto', '2'),
       ('Scottish Fold', '2'),
       ('Sphynx', '2'),
       ('Birmanês', '2'),
       ('Norueguês da Floresta', '2'),
       ('Ragamuffin', '2'),
       ('Siberiano', '2'),
       ('Burmês', '2'),
       ('Devon Rex', '2'),
       ('Chartreux', '2'),
       ('Tonquinês', '2'),
       ('Bengal', '2'),
       ('Bombay', '2'),
       ('Oriental de Pelo Curto', '2'),
       ('Balinês', '2'),
       ('Cornish Rex', '2'),
       ('Peterbald', '2'),
       ('Somali', '2'),
       ('Manx', '2'),
       ('Gato das Montanhas Rochosas', '2'),
       ('Azul Russo', '2'),
       ('Singapura', '2'),
       ('Pixie-Bob', '2'),
       ('Havana Brown', '2'),
       ('Selkirk Rex', '2'),
       ('Gato do Sri Lanka', '2'),
       ('Angorá Turco', '2'),
       ('Van Turco', '2'),
       ('Toyger', '2'),
       ('Munchkin', '2'),
       ('Gato-de-bengala', '2'),
       ('LaPerm', '2'),
       ('Scottish Fold', '2'),
       ('S.R.D. (Sem Raça Definida)', '3'),
       ('Outro', '3'),
       ('Canário', '3'),
       ('Papagaio', '3'),
       ('Periquito Australiano', '3'),
       ('Calopsita', '3'),
       ('Agapornis', '3'),
       ('Cacatua', '3'),
       ('Caturrita', '3'),
       ('Diamante-de-gould', '3'),
       ('Mandarim', '3'),
       ('Agapornis Fischeri', '3'),
       ('Agapornis Personatus', '3'),
       ('Agapornis Roseicollis', '3'),
       ('Arara', '3'),
       ('Calafate', '3'),
       ('Periquito-rei', '3'),
       ('Periquito-rico', '3'),
       ('Rosela', '3'),
       ('Forpus', '3'),
       ('Pintassilgo', '3'),
       ('Agapornis Lilianae', '3'),
       ('Agapornis Nigrigenis', '3'),
       ('Agapornis Taranta', '3'),
       ('Pardal', '3'),
       ('Curió', '3'),
       ('Coleiro', '3'),
       ('Sabiá', '3'),
       ('Bico-de-lacre', '3'),
       ('Azulão', '3'),
       ('Canário-da-terra', '3'),
       ('Sanhaço', '3'),
       ('Trinca-ferro', '3'),
       ('Canário Belga', '3'),
       ('Canário Arlequim Português', '3'),
       ('Canário Lizard', '3'),
       ('Agapornis Swindernianus', '3'),
       ('Agapornis Pullarius', '3'),
       ('Agapornis Cana', '3'),
       ('Agapornis Abyssinicus', '3'),
       ('Agapornis Nigrigenis', '3'),
       ('Agapornis Personatus', '3'),
       ('Outro', '4');

